#!/usr/bin/env python3
"""Regenerate ``clipsync/_syncthing_hashes.py`` for a Syncthing version.

Run this whenever ``config.SYNCTHING_VERSION`` is bumped:

    python tools/refresh_syncthing_hashes.py v2.0.17

It fetches Syncthing's ``sha256sum.txt.asc`` and hands it to the app's own
:func:`clipsync.syncthing._verify_release_signature`, so it writes nothing
unless the PGP signature verifies against the release key pinned in
``clipsync/_release_key.py``.

This needs gpg on PATH. That is the point of doing it here: verification
happens once, on a maintainer's machine, at release-prep time, instead of on
every end user's machine where gpg usually does not exist and the check
quietly degraded to hash-only.
"""

from __future__ import annotations

import json
import re
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from clipsync import syncthing  # noqa: E402
from clipsync._release_key import SYNCTHING_RELEASE_FINGERPRINT  # noqa: E402

_ARCHIVE_RE = re.compile(r"^syncthing-(windows|macos|linux)-[a-z0-9]+-v[\d.]+\.(zip|tar\.gz)$")
_TARGET = Path(__file__).resolve().parent.parent / "clipsync" / "_syncthing_hashes.py"

_HEADER = '''"""SHA-256 hashes of the pinned Syncthing release archives.

Generated by ``tools/refresh_syncthing_hashes.py``, which fetches
Syncthing's ``sha256sum.txt.asc`` and refuses to emit anything unless the
PGP signature verifies against the pinned release key in
``_release_key.py``. Do not hand-edit: regenerate.

Why these live in the source tree rather than being fetched at runtime:
verifying the signature at runtime needs gpg on PATH, and most end users
do not have it (stock Windows and macOS ship without it), so that check
silently degraded to hash-only. Pinning moves the trust anchor into code
that goes through review and git history, and removes the network from
the verification path entirely for the pinned version.
"""

from __future__ import annotations

SYNCTHING_PINNED_SHA256: dict[str, dict[str, str]] = {
'''


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__)
        return 2
    version = argv[1] if argv[1].startswith("v") else f"v{argv[1]}"

    if not (shutil.which("gpg") or shutil.which("gpg2")):
        print(
            "ERROR: gpg not found on PATH. This tool exists to verify the "
            "release signature, so it will not run without one.\n"
            "Install it (macOS: brew install gnupg, Debian: apt install gnupg).",
            file=sys.stderr,
        )
        return 1

    print(f"Fetching sha256sum.txt.asc for {version} ...")
    asc = syncthing._download(syncthing._asc_url(version))

    # Raises unless there is a VALIDSIG from exactly the pinned fingerprint.
    syncthing._verify_release_signature(asc)
    print(f"Signature verified against {SYNCTHING_RELEASE_FINGERPRINT}")

    sums = syncthing._parse_sha256sums(asc)
    archives = {k: v for k, v in sums.items() if _ARCHIVE_RE.match(k)}
    if not archives:
        print("ERROR: no release archives found in the signed sums file", file=sys.stderr)
        return 1

    existing: dict[str, dict[str, str]] = {}
    if _TARGET.exists():
        namespace: dict[str, object] = {}
        exec(compile(_TARGET.read_text(), str(_TARGET), "exec"), namespace)  # noqa: S102
        existing = dict(namespace.get("SYNCTHING_PINNED_SHA256", {}))  # type: ignore[arg-type]
    existing[version] = archives

    body = []
    for ver in sorted(existing):
        body.append(f'    "{ver}": {{')
        for name in sorted(existing[ver]):
            body.append(f'        "{name}": "{existing[ver][name]}",')
        body.append("    },")
    _TARGET.write_text(_HEADER + "\n".join(body) + "\n}\n")
    print(f"Wrote {len(archives)} hashes for {version} to {_TARGET}")
    print(json.dumps(sorted(archives), indent=2)[:200] + " ...")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
